### PR TITLE
Feature(s) Add: Collections Page

### PR DESCRIPTION
**Pull request by Jaagrav**
## Feature: Collections Page

https://user-images.githubusercontent.com/52719271/127741782-c92167ac-5278-40bc-b541-8c1c300c2038.mp4

### Todo
- [x] Drag and drop Collections and Bookmarks among collections
- [x] Glassmorphism, well here the glass isn't frosted but it's transparent XD
- [x] Show bookmarks on collections as well
- [x] Add new bookmarks to collection
- [x] Add new collection
- [x] Store dnd data on localstorage
- [x] Remember order and data stored using a state variable

### CODE REVIEW

**Comment by Jaagrav** [comment]
@saviomartin Why are the deploy previews failing? What does vercel have to say???

**Review by saviomartin — APPROVED** [review]

**Comment by saviomartin** [comment]
Let's give a try again @Jaagrav , Hope vercel will go fine now

**Comment by Jaagrav** [comment]
Why does it keep failing, @saviomartin can you post the screenshot of the deploy preview console please?

**Comment by Jaagrav** [comment]
The build was failing due to some issues and mistakes I made in the file system that have been fixed in the last commit.
image

Hopefully once you authorize it works.

**Comment by Jaagrav** [comment]
Marked this draft for the time being, if the deploy preview is successful then I'll update the docs and then you can merge it to `main branch`

**Comment by Jaagrav** [comment]
You can now go ahead an safely merge this PR @saviomartin

**Comment by saviomartin** [comment]
This is awesome! Works like a charm! Well done @Jaagrav

**Pull request merged**
